name: Python Package using Conda

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        environment-file: environment.yml
        python-version: 3.10
    - name: Install dependencies
      run: |
        conda activate myenv
        pip install -r requirements.txt
    - name: Run script
      run: |
        python my_script.py
